resources:
  pipelines:
    - pipeline: buildPipeline
      source: 'docker-ci'  # CI pipeline name
      trigger:
        branches:
          include:
            - main

trigger: none  # Prevents this pipeline from running on code push

stages:
- stage: DeployDev
  displayName: Deploy to Dev
  dependsOn: []
  condition: succeeded()
  jobs:
  - deployment: HelmDeployDev
    environment: dev
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'aks-dev-connect'
              azureResourceGroup: 'datahub-dev_group'
              kubernetesCluster: 'datahub-dev-lt (datahub-dev_group)'
              namespace: 'dev'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/nodejs-app'
              releaseName: 'az-node-dev'
              overrideValues: '-f .azure-pipelines/helm-values/dev-values.yaml'
              install: true

- stage: DeployTest
  displayName: Deploy to Test
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - deployment: HelmDeployTest
    environment: test
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'aks-dev-connect'
              azureResourceGroup: 'datahub-dev_group'
              kubernetesCluster: 'datahub-dev-lt (datahub-dev_group)'
              namespace: 'test'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/nodejs-app'
              releaseName: 'az-node-test'
              overrideValues: '-f .azure-pipelines/helm-values/test-values.yaml'
              install: true

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - deployment: HelmDeployProd
    environment: prod  # Configure approval in Azure DevOps UI
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'aks-dev-connect'
              azureResourceGroup: 'datahub-dev_group'
              kubernetesCluster: 'datahub-dev-lt (datahub-dev_group)'
              namespace: 'prod'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/nodejs-app'
              releaseName: 'az-node-prod'
              overrideValues: '-f .azure-pipelines/helm-values/prod-values.yaml'
              install: true
