resources:
  pipelines:
    - pipeline: buildPipeline
      source: 'docker-ci'  # CI pipeline
      trigger:
        branches:
          include:
            - main
stages:
- stage: DeployDev
  displayName: Deploy to Dev
  jobs:
  - deployment: HelmDeployDev
    environment: dev
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'aks-dev-connect'
              azureResourceGroup: 'datahub-dev_group'
              kubernetesCluster: 'datahub-dev-lt (datahub-dev_group)'
              namespace: 'dev'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/your-app'
              releaseName: 'az-node-dev'
              overrideValues: '-f .azure-pipelines/helm-values/dev-values.yaml'
              install: true

- stage: DeployTest
  displayName: Deploy to Test
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - deployment: HelmDeployTest
    environment:
      name: test
      resourceName: test
      action: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              # similar as above, with test-specific values and namespace
              namespace: 'test'
              overrideValues: '-f .azure-pipelines/helm-values/test-values.yaml'

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployTest
  condition: succeeded()
  approval:
    approvals:
      - reviewers:
        - <Azure DevOps user email or group>
  jobs:
  - deployment: HelmDeployProd
    environment: prod
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            inputs:
              namespace: 'prod'
              overrideValues: '-f .azure-pipelines/helm-values/prod-values.yaml'
