resources:
  pipelines:
    - pipeline: buildPipeline
      source: 'docker-ci'
      trigger:
        branches:
          include:
            - main

trigger: none

stages:
- stage: DeployDev
  displayName: Deploy to Dev
  dependsOn: []
  condition: succeeded()
  jobs:
  - deployment: HelmDeployDev
    environment: dev
    pool:
      name: default          # agent pool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'
          - task: HelmDeploy@0
            displayName: 'Deploy via Helm'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'aks-dev-connect'
              namespace: 'dev'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/your-app'
              releaseName: 'az-node-dev'
              overrideValues: '-f .azure-pipelines/helm-values/dev-values.yaml'
              install: true

- stage: DeployTest
  displayName: Deploy to Test
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - deployment: HelmDeployTest
    environment: test
    pool:
      name: default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'
          - task: HelmDeploy@0
            displayName: 'Deploy via Helm'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'aks-dev-connect'
              namespace: 'test'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/your-app'
              releaseName: 'az-node-test'
              overrideValues: '-f .azure-pipelines/helm-values/test-values.yaml'
              install: true

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - deployment: HelmDeployProd
    environment: prod    # approvals
    pool:
      name: default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'
          - task: HelmDeploy@0
            displayName: 'Deploy via Helm'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'aks-dev-connect'
              namespace: 'prod'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'charts/your-app'
              releaseName: 'az-node-prod'
              overrideValues: '-f .azure-pipelines/helm-values/prod-values.yaml'
              install: true
